POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name": "heehe",
    "email": "abcdfe@gmail.com",
    "password": "1234344"
}

###
GET http://localhost:8080/api/v1/users?current=1&pageSize=2&sort='-createAt'

###
PATCH http://localhost:8080/api/v1/users
Content-Type: application/json

{ 
   "_id": "66c41eefcda078e43c79dc1b",
   "name": "update name",
   "phone":"032564897",
   "address":"update address"
}

###
DELETE http://localhost:8080/api/v1/users/66c43b7e509a7978257b33c5

###
POST  http://localhost:8080/api/v1/auth/log-in
Content-Type: application/json

{
    "email": "abcdfe@gmail.com",
    "password": "1234344"
}